export const EMPLOYEE_SUCCESS = "EMPLOYEE_SUCCESS"
export const EMPLOYEE_FAIL = "EMPLOYEE_FAIL"
export const EMPLOYEE_REQUEST = "EMPLOYEE_REQUEST"


export const POST_COMPANY = "POST_COMPANY"
export const POST_FAIL = "POST_FAIL"
export const POST_REQUEST = "POST_REQUEST"


export const GET_COMPANYID = "GET_COMPANYID"
export const COMPANY_FAIL = "COMPANY_FAIL"
export const COMPANY_REQUEST = "COMPANY REQUEST"

export const UPDATE_COMPANYID = "UPDATE_COMPANYID"
export const UPDATE_FAIL = "UPDATE_FAIL"
export const UPDATE_REQUEST = "UPDATE_REQUEST"